# Generated by Django 5.0.3 on 2026-04-20 15:42

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Cliente',
                'verbose_name_plural': 'Tipos de Clientes',
            },
        ),
        migrations.CreateModel(
            name='DetectionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Origem da Detecção',
                'verbose_name_plural': 'Origens da Detecção',
            },
        ),
        migrations.CreateModel(
            name='HistoricalIncident',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('mk_protocol', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('occured_at', models.DateTimeField()),
                ('expected_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_history_update_at', models.DateTimeField(blank=True, null=True)),
                ('is_impact_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('rfo', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Incidente',
                'verbose_name_plural': 'historical Incidentes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUpdateIncident',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('is_impact_active', models.BooleanField(verbose_name='Impacto Ativo?')),
                ('comment', models.TextField(verbose_name='Nota Técnica')),
                ('time_elapsed', models.IntegerField(blank=True, default=0, help_text='Minutos decorridos desde a última atualização (ou desde a abertura)', null=True, verbose_name='Tempo decorrido (Minutos)')),
                ('is_new_comment', models.BooleanField(default=False)),
                ('is_new_status', models.BooleanField(default=False)),
                ('is_new_expected_at', models.BooleanField(default=False)),
                ('is_new_impact_level', models.BooleanField(default=False)),
                ('is_new_impact_type', models.BooleanField(default=False)),
                ('is_opening', models.BooleanField(default=False)),
                ('is_closing', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Atualização de Incidente',
                'verbose_name_plural': 'historical Atualizações de Incidente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ImpactLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Nível de Impacto',
                'verbose_name_plural': 'Níveis de Impacto',
            },
        ),
        migrations.CreateModel(
            name='ImpactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Impacto',
                'verbose_name_plural': 'Tipos de Impactos',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('mk_protocol', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('occured_at', models.DateTimeField()),
                ('expected_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_history_update_at', models.DateTimeField(blank=True, null=True)),
                ('is_impact_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('rfo', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Incidente',
                'verbose_name_plural': 'Tipos de Incidentes',
            },
        ),
        migrations.CreateModel(
            name='RegionImpactIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('impact_severity', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Impacto Regional',
                'verbose_name_plural': 'Impactos Regionais',
            },
        ),
        migrations.CreateModel(
            name='RootCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Causa Raiz',
                'verbose_name_plural': 'Causas Raiz',
            },
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='Padrão', max_length=50)),
            ],
            options={
                'verbose_name': 'SLA',
                'verbose_name_plural': 'SLAs',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Sintoma',
                'verbose_name_plural': 'Sintomas',
            },
        ),
        migrations.CreateModel(
            name='UpdateIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_impact_active', models.BooleanField(verbose_name='Impacto Ativo?')),
                ('comment', models.TextField(verbose_name='Nota Técnica')),
                ('time_elapsed', models.IntegerField(blank=True, default=0, help_text='Minutos decorridos desde a última atualização (ou desde a abertura)', null=True, verbose_name='Tempo decorrido (Minutos)')),
                ('is_new_comment', models.BooleanField(default=False)),
                ('is_new_status', models.BooleanField(default=False)),
                ('is_new_expected_at', models.BooleanField(default=False)),
                ('is_new_impact_level', models.BooleanField(default=False)),
                ('is_new_impact_type', models.BooleanField(default=False)),
                ('is_opening', models.BooleanField(default=False)),
                ('is_closing', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Atualização de Incidente',
                'verbose_name_plural': 'Atualizações de Incidente',
                'ordering': ['-created_at'],
            },
        ),
    ]
