# Generated by Django 5.0.3 on 2026-04-20 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('netbox', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='circuit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='netbox.circuit'),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='client_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidents.clienttype'),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='detection_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidents.detectionsource'),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='device',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='netbox.device'),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='netbox.site'),
        ),
        migrations.AddField(
            model_name='historicalupdateincident',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='historicalupdateincident',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='impact_level',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidents.impactlevel'),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='impact_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidents.impacttype'),
        ),
        migrations.AddField(
            model_name='incident',
            name='affected_regions',
            field=models.ManyToManyField(blank=True, related_name='incidents_affected', to='netbox.region', verbose_name='Cidades/Regiões Afetadas'),
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='circuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox.circuit'),
        ),
        migrations.AddField(
            model_name='incident',
            name='client_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidents.clienttype'),
        ),
        migrations.AddField(
            model_name='incident',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='detection_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='incidents.detectionsource'),
        ),
        migrations.AddField(
            model_name='incident',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox.device'),
        ),
        migrations.AddField(
            model_name='incident',
            name='impact_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidents.impactlevel'),
        ),
        migrations.AddField(
            model_name='incident',
            name='impact_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidents.impacttype'),
        ),
        migrations.AddField(
            model_name='incident',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox.site'),
        ),
        migrations.AddField(
            model_name='historicalupdateincident',
            name='incident',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidents.incidenttype'),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='incident_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidents.incidenttype'),
        ),
        migrations.AddField(
            model_name='regionimpactincident',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='regionimpactincident',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox.region'),
        ),
        migrations.AddField(
            model_name='incident',
            name='root_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='incidents.rootcause'),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='root_cause',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidents.rootcause'),
        ),
        migrations.AddField(
            model_name='incident',
            name='sla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidents.sla'),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='sla',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidents.sla'),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidents.status'),
        ),
        migrations.AddField(
            model_name='historicalupdateincident',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidents.status'),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidents.status'),
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_symptom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='incidents.symptom'),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='reported_symptom',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidents.symptom'),
        ),
        migrations.AddField(
            model_name='updateincident',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='updateincident',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='updateincident',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidents.status'),
        ),
        migrations.AlterUniqueTogether(
            name='regionimpactincident',
            unique_together={('incident', 'region')},
        ),
    ]
