# Generated by Django 5.0.3 on 2026-04-20 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#6c757d', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Tag de Atualização',
                'verbose_name_plural': 'Tags de Atualização',
            },
        ),
        migrations.RemoveField(
            model_name='historicalupdateincident',
            name='is_closing',
        ),
        migrations.RemoveField(
            model_name='historicalupdateincident',
            name='is_new_comment',
        ),
        migrations.RemoveField(
            model_name='historicalupdateincident',
            name='is_new_expected_at',
        ),
        migrations.RemoveField(
            model_name='historicalupdateincident',
            name='is_new_impact_level',
        ),
        migrations.RemoveField(
            model_name='historicalupdateincident',
            name='is_new_impact_type',
        ),
        migrations.RemoveField(
            model_name='historicalupdateincident',
            name='is_new_status',
        ),
        migrations.RemoveField(
            model_name='historicalupdateincident',
            name='is_opening',
        ),
        migrations.RemoveField(
            model_name='updateincident',
            name='is_closing',
        ),
        migrations.RemoveField(
            model_name='updateincident',
            name='is_new_comment',
        ),
        migrations.RemoveField(
            model_name='updateincident',
            name='is_new_expected_at',
        ),
        migrations.RemoveField(
            model_name='updateincident',
            name='is_new_impact_level',
        ),
        migrations.RemoveField(
            model_name='updateincident',
            name='is_new_impact_type',
        ),
        migrations.RemoveField(
            model_name='updateincident',
            name='is_new_status',
        ),
        migrations.RemoveField(
            model_name='updateincident',
            name='is_opening',
        ),
        migrations.AddField(
            model_name='historicalupdateincident',
            name='expected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalupdateincident',
            name='impact_level',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidents.impactlevel'),
        ),
        migrations.AddField(
            model_name='historicalupdateincident',
            name='impact_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidents.impacttype'),
        ),
        migrations.AddField(
            model_name='updateincident',
            name='expected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updateincident',
            name='impact_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='incidents.impactlevel'),
        ),
        migrations.AddField(
            model_name='updateincident',
            name='impact_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='incidents.impacttype'),
        ),
        migrations.AlterField(
            model_name='historicalupdateincident',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Nota Técnica'),
        ),
        migrations.AlterField(
            model_name='updateincident',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Nota Técnica'),
        ),
        migrations.AddField(
            model_name='updateincident',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='updates', to='incidents.updatetag'),
        ),
    ]
