# Generated by Django 5.0.3 on 2026-04-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_updatetag_remove_historicalupdateincident_is_closing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincident',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
