# Generated by Django 5.0.3 on 2026-04-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_historicalincident_stopped_at_incident_stopped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalupdateincident',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updateincident',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
