# Generated by Django 5.0.3 on 2026-04-22 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_historicalupdateincident_stopped_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='client_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='incidents.clienttype'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='impact_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='incidents.impactlevel'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='impact_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='incidents.impacttype'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='sla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='incidents.sla'),
        ),
    ]
