# Generated by Django 5.0.3 on 2026-04-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_alter_incident_client_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalupdateincident',
            name='user_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da Atualização'),
        ),
        migrations.AddField(
            model_name='updateincident',
            name='user_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da Atualização'),
        ),
    ]
