# Generated by Django 5.0.3 on 2026-04-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_alter_updateincident_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincident',
            name='last_manual_update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='last_manual_update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
