# Generated by Django 5.0.3 on 2026-04-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_historicalincident_last_manual_update_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincident',
            name='provider_protocol',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Protocolo Operadora'),
        ),
        migrations.AddField(
            model_name='incident',
            name='provider_protocol',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Protocolo Operadora'),
        ),
    ]
