# Generated by Django 5.0.3 on 2026-04-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_historicalincident_provider_protocol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincident',
            name='no_provider_protocol',
            field=models.BooleanField(default=False, verbose_name='Fornecedor não gerou protocolo'),
        ),
        migrations.AddField(
            model_name='incident',
            name='no_provider_protocol',
            field=models.BooleanField(default=False, verbose_name='Fornecedor não gerou protocolo'),
        ),
    ]
