# Generated by Django 5.0.3 on 2026-04-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0011_historicalincident_no_provider_protocol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincident',
            name='protocol_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='protocol_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.RunSQL(
            sql="""
            CREATE SEQUENCE IF NOT EXISTS incident_protocol_seq START 1;

            CREATE OR REPLACE FUNCTION generate_incident_protocol()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.protocol_number IS NULL OR NEW.protocol_number = '' THEN
                    NEW.protocol_number := 'SEA-' || LPAD(nextval('incident_protocol_seq')::text, 6, '0');
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER trg_generate_incident_protocol
            BEFORE INSERT ON incidents_incident
            FOR EACH ROW
            EXECUTE FUNCTION generate_incident_protocol();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_generate_incident_protocol ON incidents_incident;
            DROP FUNCTION IF EXISTS generate_incident_protocol();
            DROP SEQUENCE IF EXISTS incident_protocol_seq;
            """
        ),
    ]
