# Generated by Django 5.0.3 on 2026-04-30 19:16

import apps.incidents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_historicalincident_protocol_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalupdateincident',
            name='attachment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='updateincident',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.incidents.models.update_attachment_path, verbose_name='Anexo'),
        ),
    ]
