# Generated by Django 5.0.3 on 2026-04-30 20:06

import apps.incidents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0013_historicalupdateincident_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalupdateincident',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='updateincident',
            name='attachment',
        ),
        migrations.CreateModel(
            name='UpdateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('file', models.FileField(upload_to=apps.incidents.models.update_attachment_path, verbose_name='Arquivo')),
                ('filename', models.CharField(editable=False, max_length=255)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments_rel', to='incidents.updateincident')),
            ],
            options={
                'verbose_name': 'Anexo de Atualização',
                'verbose_name_plural': 'Anexos de Atualização',
            },
        ),
        migrations.AddField(
            model_name='updateincident',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='updates', to='incidents.updateattachment'),
        ),
    ]
